plugins {
    id 'fabric-loom' version "${loom_version}"
}

version = project.version
group = project.maven_group

base {
    archivesName = project.mod_id
}

repositories {
    mavenCentral()
    maven { url = "https://maven.parchmentmc.org" }
}

loom {
    def aw = file("src/main/resources/${project.mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mixin {
        useLegacyMixinAp = true
        defaultRefmapName.set("${mod_id}.refmap.json")
    }

    runs {
        client {
            client()
            runDir('runs/client')
        }
        server {
            server()
            runDir('runs/server')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.mc_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.parchment_minecraft}:${project.parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation("org.reflections:reflections:0.10.2")
    include("org.reflections:reflections:0.10.2")

    implementation("org.javassist:javassist:3.29.2-GA")
    include("org.javassist:javassist:3.29.2-GA")
}

processResources {
    inputs.property "version", project.version
    inputs.property "mod_id", project.mod_id
    inputs.property "mod_description", project.mod_description
    inputs.property "mod_full_name", project.mod_full_name
    inputs.property "license", project.license
    inputs.property "mc_version", project.mc_version
    inputs.property "fabric_version", project.fabric_version
    inputs.property "fabric_loader_version", project.fabric_loader_version
    inputs.property "java_version", project.java_version
    inputs.property "mc_version_range_fabric", project.mc_version_range_fabric

    filesMatching("fabric.mod.json") {
        expand(
            "version": project.version,
            "mod_id": project.mod_id,
            "mod_full_name": project.mod_full_name,
            "mod_description": project.mod_description,
            "license": project.license,
            "mc_version": project.mc_version,
            "fabric_version": project.fabric_version,
            "fabric_loader_version": project.fabric_loader_version,
            "java_version": project.java_version,
            "mc_version_range_fabric": project.mc_version_range_fabric
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}
